### ISSUE TITLE
Multiblup: After step 6, how to use the prediction model to predict the phenotype of test data

### ISSUE THREAD

**Issue by jiefangDuan** [belowlab/ldak#1]
Thank you very much for developing this application, which is very helpful to my work.
    I use trainfile successfully run a six step procedure, as you wrote on https://dougspeed.com/multiblup. it can work normally, and created    train.blup,    train.blup.Full,    train.pred,    train.pred.full .
   Now, I need to make predictions for my new sample. How do I apply the prediction model to TestFile?
   I am sorry that I am still not proficient in using the software. Thanks for helping me solve this problem.

**Comment by pettyalex** [comment]
Hello @jiefangDuan, 

This is not the main development repository for LDAK, just a copy that I put up to develop & test some improvements to it. You can reach out to Doug Speed for assistance, his contact information is here: https://dougspeed.com/help/

Good luck!

**Comment by jiefangDuan** [comment]
Thank you for your kind answer and help.
